// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/Proto2Test.proto

package com.example.grpc.api;

public interface FooOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Foo)
    com.google.protobuf.MessageOrBuilder {
}
