// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/Proto2Test.proto

package com.example.grpc.api;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string query = 1;</code>
   * @return Whether the query field is set.
   */
  boolean hasQuery();
  /**
   * <code>optional string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>optional string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>optional int32 page_number = 2;</code>
   * @return Whether the pageNumber field is set.
   */
  boolean hasPageNumber();
  /**
   * <code>optional int32 page_number = 2;</code>
   * @return The pageNumber.
   */
  int getPageNumber();

  /**
   * <code>optional int32 result_per_page = 3;</code>
   * @return Whether the resultPerPage field is set.
   */
  boolean hasResultPerPage();
  /**
   * <code>optional int32 result_per_page = 3;</code>
   * @return The resultPerPage.
   */
  int getResultPerPage();
}
