#logging:
#  level:
#    root: DEBUG
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: test_gateway
          uri: http://127.0.0.1:8011/order/getorder
          predicates:
            - Path=/order/*
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gatway-demo

server:
  port: 8081



